language: node_js
node_js:
  - 10.16.0

install:
  - npm install  

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: github pages
      script: PUBLIC_URL=./ npm run build
      deploy:
        provider: pages
        local_dir: build
        verbose: true
        skip_cleanup: true
        github_token: $GH_PAGE_DEPLOY_TOKEN
        keep_history: true
        committer_from_gh: true
      if: branch = master
