name: Publish release

on:
  push:
    branches: [ master ]
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: 'Version to publish'
  #       required: true

jobs:
  npm-publish:
    name: publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.8'

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1

      - name: publish to npm
        if: steps.check.outputs.changed == 'true'
        run: echo "would publish to npm"
